on:
  push:
    branches:
      - main
name: Publish web
jobs:
  publish_web:
    concurrency:
      group: publish_web
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup show
      - run: wget -qO- https://github.com/thedodd/trunk/releases/download/v0.14.0/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
      - run: mv trunk /usr/local/bin
      - run: trunk build --release
      - uses: crazy-max/ghaction-github-pages@v2
        if: success()
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
